### PR TITLE
Use events from middleware-dispatcher

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | https://github.com/yiisoft/yii-web/pull/344

### CODE REVIEW

**Comment by rustamwin** [comment]
The tests also should be fixed.

**Comment by samdark** [comment]
@rustamwin it's not related. Tests are failing the same way as they do in master.

**Comment by samdark** [comment]
Static analysis fails because middleware-dispatcher changes aren't in master yet.

**Comment by rustamwin** [comment]
> @rustamwin it's not related. Tests are failing the same way as they do in master. Seems they may be unstable.

Oh. You're right.

**Pull request merged**
