### PR TITLE
Fix #282: Don't dump objects that are absent in the objects cache

### LINKED ISSUE #282: Dumper::asJsonObjectsMap() produces out of memory error
### What steps will reproduce the problem?
run this app https://github.com/olegbaturin/yii3-app-api

Ошибка в алгоритме и довольно нетривиальная, опишу на русском.

https://github.com/yiisoft/yii-debug/blob/7e1c7050de7ef32de22e4f179432def52713d70c/src/Dumper.php#L62
Метод `buildObjectsCache()` проходит на заданную глубину `$depth` и строит плоский массив из всей вложенной структуры объектов, который сохраняет в `$this->objects`. Алгоритм также отслеживает циклические зависимости вида parent->child->parent.
Таким образом оказывается, что объект с заданной максимальной глубины вложенности `$depth` оказывается на первом уровне.

https://github.com/yiisoft/yii-debug/blob/7e1c7050de7ef32de22e4f179432def52713d70c/src/Dumper.php#L59
Далее происходит этот вызов и каждый элемент из `$this->objects` в методе `asJsonInternal()` еще раз парсится на глубину `$depth`. Получается, что элемент из массива `$this->objects` с глубины `$depth` будет парситься повторно на эту же глубину `$depth`, т.е. в итоге `2* $depth`.

https://github.com/yiisoft/yii-debug/blob/7e1c7050de7ef32de22e4f179432def52713d70c/src/Dumper.php#L162
Ошибка возникает из-за того, что в этой проверке предполагается, что все объекты уже есть в кэшэ, т.е. в массиве `$this->objects`. Это не так, потому что `$this->objects` содержит объекты с глубины только `$depth`, а парсинг делается на глубину `2* $depth`. Также метод `dumpNestedInternal()` не отслеживает цикличекские зависимости `parent->child->parent`.

Если конфигурация приложения содержит циклические зависимости `parent->child->parent` , то происходит цикличкский дамп до глубины `2* $depth` без учёта вложенных дублей.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | any
| Operating system | any

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

#282

### CODE REVIEW

**Comment by samdark** [comment]
TODO:

- [ ] Verify with @xepozz result is expected.
- [ ] Adjust expected structures in tests.

**Comment by xepozz** [comment]
image
It’s the wrong way to fix the issue. Nested objects are collapsed by default.

**Comment by xepozz** [comment]
See https://github.com/yiisoft/yii-debug/issues/282#issuecomment-2453608177

**Comment by xepozz** [comment]
Current solution generates the following output for my test case:
```
{
  "stdClass#2488": {
    "public $objects": [],
    "public $id": "lvl1",
    "public $prop1": "object@stdClass#721",
    "public $prop2": "object@stdClass#721"
  },
  "stdClass#721": {
    "public $id": "lvl2",
    "public $prop1": "object@stdClass#2245",
    "public $prop2": "object@stdClass#2245"
  },
  "stdClass#2245": {
    "public $id": "lvl3",
    "public $prop1": "object@stdClass#2238",
    "public $prop2": "object@stdClass#2238"
  },
  "stdClass#2238": {
    "public $id": "lvl4",
    "public $prop1": "stdClass#2246 (...)",
    "public $prop2": "stdClass#2246 (...)"
  }
}
```
It could be as a temporary solution, but I'd like to go to the max depth and collect all possible values

**Comment by olegbaturin** [comment]
> I'd like to go to the max depth and collect all possible values

You can't go deeper because max depth is 5 and Dumper must stop on level 5.

**Comment by samdark** [comment]
@xepozz, @olegbaturin should this one be closed?

**Pull request closed without merging**
