### PR TITLE
Add `yiisoft/view` `^5.0` version support

### PR DESCRIPTION
**Pull request by rustamwin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ❌
| Fixed issues  | #126

### CODE REVIEW

**Comment by vjik** [comment]
[Open PRs](https://github.com/yiisoft/view/pulls) in Yii View breaking backward compatibility, so soon will be major release. Suggest wait release, and then add support `^6.0` version also.

**Comment by rustamwin** [comment]
> [Open PRs](https://github.com/yiisoft/view/pulls) in Yii View breaking backward compatibility, so soon will be major release. Suggest wait release, and then add support ^6.0 version also.

Looks like there is no major release.

**Comment by vjik** [comment]
> > [Open PRs](https://github.com/yiisoft/view/pulls) in Yii View breaking backward compatibility, so soon will be major release. Suggest wait release, and then add support ^6.0 version also.
> 
> Looks like there is no major release.

`[BC] ADDED: Method withBasePath() was added to interface Yiisoft\View\ViewInterface`

**Review by samdark — APPROVED** [review]

**Comment by rustamwin** [comment]
> [BC] ADDED: Method withBasePath() was added to interface Yiisoft\View\ViewInterface

It doesn't break yii-debug.

**Pull request merged**
